image: Ubuntu

branches:
  only:
    - master

build: off

install:

  - ps: chmod +x gradlew
build_script:

  - ps: ./gradlew test --info "-Dselenide.headless=true"

on_finish:
  - ps: Stop-Process -Id $App.Id